### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by paulafuruyama** [chrisbjr/philippine-income-tax-android#1]
1.  On landscape, values become zero  (net income, sss, etc)
2. When erasing values in monthly salary value  from net income and tax does not change.
   @johneris

**Comment by johneris** [comment]
@chrisbjr are we going to support landscape?

**Comment by chrisbjr** [comment]
@johneris sige, to fix this, let's just prevent landscape. Wala rin naman tayo makita pag landscape sa mobile phone.

**Comment by chrisbjr** [comment]
Thanks @johneris
